### ISSUE TITLE
[FEATURES]If the environment is used by multi users , users creating alluxioruntime at the same time will cause  conflict

### ISSUE THREAD

**Issue by yangyuliufeng** [fluid-cloudnative/fluid#323] opened 2020-11-03 08:54 UTC
**What feature you'd like to add:**
kubernetes version：
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.9-aliyun.1", GitCommit:"4f7ea78", GitTreeState:"", BuildDate:"2020-05-08T07:35:38Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.9-aliyun.1", GitCommit:"4f7ea78", GitTreeState:"", BuildDate:"2020-05-08T07:29:59Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

fluid version：
BuildDate: 2020-11-01_15:00:37
GitCommit: 1c40aeec4439198ebbd43987f4d7fea69d46f70a

When do test in https://github.com/fluid-cloudnative/fluid/blob/master/docs/zh/samples/multi_dataset_same_node_accessing.md
if  create  runtime1.yaml right after creating runtime.yaml，the ports of hbase worker and spark worker will conflict
![image](https://user-images.githubusercontent.com/30432274/97965331-1a721380-1db2-11eb-8961-e17692227a47.png)

**Why is this feature needed:**
If the environment is used by multi users , users creating alluxioruntime at the same time will cause  conflict

**Comment by xieydd** [comment] 2020-11-03 13:33
@yangyuliufeng  Thanks for your feed back. When you wait for hbase runtime component all running and create spark runtime, will have port conflict error?

**Comment by xieydd** [comment] 2021-08-17 02:23
I think the issue is fixed, how about closing the issue.

**Comment by TrafalgarZZZ** [comment] 2022-04-02 06:30
Global port allocator is added in #727. So I think the port conflict is resolved now. Closing it.

**Closed by TrafalgarZZZ** 2022-04-02 06:30 UTC
Labels: features, v0.5.0
