### ISSUE TITLE
[BUG] Dataload can`t full load data

### ISSUE THREAD

**Issue by xieydd** [fluid-cloudnative/fluid#633] opened 2021-03-14 11:26 UTC
**What is your environment(Kubernetes version, Fluid version, etc.)**
version: 0.4.0
commit id: 51b6a44c3c6bcc1bc828aaaa6c020f2627bb0553
**Describe the bug**
When i ran dataload job completely, the dataset is not fully loaded.
```
apiVersion: data.fluid.io/v1alpha1
kind: DataLoad
metadata:
  name: slice1-dataload
spec:
  dataset:
    name: slice1
    namespace: default
  loadMetadata: true
  target:
    - path: /
      replicas: 1
```

```
slice1-dataload-loader-job-7rrpz   0/1     Completed   0          46m   10.16.0.166     10.16.100.234   <none>           1/1
NAME     UFS TOTAL SIZE   CACHED      CACHE CAPACITY   CACHED PERCENTAGE   PHASE   AGE
slice1   300.31GiB        171.93GiB   400.00GiB        57.3%               Bound   73m
```

This is dataload full log: 
[dataload.log](https://github.com/fluid-cloudnative/fluid/files/6136572/dataload.log)

**Comment by xieydd** [comment] 2021-03-14 11:26
link:  https://github.com/fluid-cloudnative/fluid/issues/633#issue-831132498

**Comment by xieydd** [comment] 2021-03-14 12:10
@cheyang cc

**Comment by xieydd** [comment] 2021-03-15 01:13
Full log here
[Uploading diagnose_fluid_1615769945.tar.gz…]()

**Comment by cheyang** [comment] 2021-03-17 07:02
@xieydd @apc999 had found the root cause, and will fix it soon.

**Comment by apc999** [comment] 2021-03-20 00:36
Merged https://github.com/Alluxio/alluxio/issues/13005, 
I will cut a new release and see if this is resolved by above fix

**Comment by xieydd** [comment] 2021-03-23 10:39
I think this error is not fixed. This is full log.
[diagnose_fluid_1616495657.tar.gz](https://github.com/fluid-cloudnative/fluid/files/6188802/diagnose_fluid_1616495657.tar.gz)

**Comment by xieydd** [comment] 2021-03-25 06:07
@apc999 @cheyang release-2.5.0-1 have this error too.

**Comment by xieydd** [comment] 2021-03-26 09:55
Add information, all data is 300GB
```
Capacity information for all workers:
    Total Capacity: 400.00GB
        Tier: MEM  Size: 400.00GB
    Used Capacity: 151.18GB
        Tier: MEM  Size: 151.18GB
    Used Percentage: 37%
    Free Percentage: 63%

Worker Name      Last Heartbeat   Storage       MEM
10.16.100.7      0                capacity      40.00GB
                                  used          15.06GB (37%)
10.16.100.162    0                capacity      40.00GB
                                  used          15.13GB (37%)
10.16.100.83     0                capacity      40.00GB
                                  used          15.13GB (37%)
10.16.100.139    0                capacity      40.00GB
                                  used          15.13GB (37%)
10.16.100.153    0                capacity      40.00GB
                                  used          15.13GB (37%)
10.16.100.62     0                capacity      40.00GB
                                  used          15.13GB (37%)
10.16.100.234    0                capacity      40.00GB
                                  used          15.13GB (37%)
10.16.100.67     0                capacity      40.00GB
                                  used          15.13GB (37%)
10.16.100.214    0                capacity      40.00GB
                                  used          15.13GB (37%)
10.16.100.254    0                capacity      40.00GB
                                  used          15.13GB (37%)
```

**Closed** 2021-04-02 07:23 UTC
Labels: bug
